//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartFridgeManagerAPI.Application.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages_en_US {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages_en_US() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SmartFridgeManagerAPI.Application.Resources.Messages_en_US", typeof(Messages_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MustBeUnique {
            get {
                return ResourceManager.GetString("MustBeUnique", resourceCulture);
            }
        }
        
        internal static string ContainInvalidCharacters {
            get {
                return ResourceManager.GetString("ContainInvalidCharacters", resourceCulture);
            }
        }
        
        internal static string MustHasSameValue {
            get {
                return ResourceManager.GetString("MustHasSameValue", resourceCulture);
            }
        }
        
        internal static string MustHasOneDigit {
            get {
                return ResourceManager.GetString("MustHasOneDigit", resourceCulture);
            }
        }
        
        internal static string MustHasOneLowercase {
            get {
                return ResourceManager.GetString("MustHasOneLowercase", resourceCulture);
            }
        }
        
        internal static string MustHasOneUppercase {
            get {
                return ResourceManager.GetString("MustHasOneUppercase", resourceCulture);
            }
        }
        
        internal static string MustHasOneSpecialCharacter {
            get {
                return ResourceManager.GetString("MustHasOneSpecialCharacter", resourceCulture);
            }
        }
        
        internal static string SendActivationEmailSubject {
            get {
                return ResourceManager.GetString("SendActivationEmailSubject", resourceCulture);
            }
        }
        
        internal static string SendActivationEmailBody {
            get {
                return ResourceManager.GetString("SendActivationEmailBody", resourceCulture);
            }
        }
        
        internal static string SendActivationEmailBodyBtn {
            get {
                return ResourceManager.GetString("SendActivationEmailBodyBtn", resourceCulture);
            }
        }
        
        internal static string RegisteredUserActivationEmailMsg {
            get {
                return ResourceManager.GetString("RegisteredUserActivationEmailMsg", resourceCulture);
            }
        }
    }
}
